In [1]:
# E-Commerce Order Fulfilment Data Platform
# Capstone Project
# Student: SHASHIKANTH
# Dataset: Brazilian E-Commerce Public Dataset by Olist

In [2]:
import pandas as pd

orders = pd.read_csv('/content/olist_orders_dataset.csv')
customers = pd.read_csv('/content/olist_customers_dataset.csv')
order_items = pd.read_csv('/content/olist_order_items_dataset.csv')
payments = pd.read_csv('/content/olist_order_payments_dataset.csv')
reviews = pd.read_csv('/content/olist_order_reviews_dataset.csv')
products = pd.read_csv('/content/olist_products_dataset.csv')
sellers = pd.read_csv('/content/olist_sellers_dataset.csv')

print("Files loaded successfully!")

Files loaded successfully!

In [3]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [4]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [5]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [6]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [7]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [8]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [9]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [10]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [11]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [12]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [13]:
payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

In [14]:
reviews.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [15]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [16]:
sellers.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

In [17]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [18]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [19]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [20]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [21]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [22]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [23]:
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [24]:
duplicate_orders = orders['order_id'].duplicated().sum()

print("Duplicate Order IDs:", duplicate_orders)

Duplicate Order IDs: 0

In [25]:
negative_price = (order_items['price'] < 0).sum()

print("Negative Prices:", negative_price)

Negative Prices: 0

In [26]:
negative_freight = (order_items['freight_value'] < 0).sum()

print("Negative Freight Values:", negative_freight)

Negative Freight Values: 0

In [27]:
negative_payment = (payments['payment_value'] < 0).sum()

print("Negative Payment Values:", negative_payment)

Negative Payment Values: 0

**SILVER LAYER (CLEANED DATA)**

In [28]:
# Create copies for Silver Layer

orders_silver = orders.copy()
customers_silver = customers.copy()
order_items_silver = order_items.copy()
payments_silver = payments.copy()
reviews_silver = reviews.copy()
products_silver = products.copy()
sellers_silver = sellers.copy()

print("Silver Layer Created Successfully")

Silver Layer Created Successfully

In [29]:
orders_silver['order_purchase_timestamp'] = pd.to_datetime(
    orders_silver['order_purchase_timestamp']
)

orders_silver['order_approved_at'] = pd.to_datetime(
    orders_silver['order_approved_at']
)

orders_silver['order_delivered_carrier_date'] = pd.to_datetime(
    orders_silver['order_delivered_carrier_date']
)

orders_silver['order_delivered_customer_date'] = pd.to_datetime(
    orders_silver['order_delivered_customer_date']
)

orders_silver['order_estimated_delivery_date'] = pd.to_datetime(
    orders_silver['order_estimated_delivery_date']
)

print("Date Conversion Completed")

Date Conversion Completed

In [30]:
orders_silver.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [31]:
orders_silver['delivery_days'] = (
    orders_silver['order_delivered_customer_date']
    - orders_silver['order_purchase_timestamp']
).dt.days

orders_silver['delay_days'] = (
    orders_silver['order_delivered_customer_date']
    - orders_silver['order_estimated_delivery_date']
).dt.days

print("Delivery KPIs Created")

Delivery KPIs Created

In [32]:
orders_silver[['delivery_days','delay_days']].head()

   delivery_days  delay_days
0            8.0        -8.0
1           13.0        -6.0
2            9.0       -18.0
3           13.0       -13.0
4            2.0       -10.0

**GOLD LAYER**

**fact_orders**

In [33]:
fact_orders = orders_silver[[
    'order_id',
    'customer_id',
    'order_status',
    'order_purchase_timestamp',
    'order_delivered_customer_date',
    'order_estimated_delivery_date',
    'delivery_days',
    'delay_days'
]].copy()

print("Fact Orders Created Successfully")
print(fact_orders.shape)

Fact Orders Created Successfully
(99441, 8)

In [34]:
fact_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delay_days
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18,8.0,-8.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-08-07 15:27:45,2018-08-13,13.0,-6.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-17 18:06:29,2018-09-04,9.0,-18.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-12-02 00:28:42,2017-12-15,13.0,-13.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-16 18:17:02,2018-02-26,2.0,-10.0

In [35]:
fact_orders.shape

(99441, 8)

**dim_customer**

In [36]:
dim_customer = customers_silver[[
    'customer_id',
    'customer_unique_id',
    'customer_city',
    'customer_state'
]].copy()

print("Dimension Customer Created")
print(dim_customer.shape)

Dimension Customer Created
(99441, 4)

In [37]:
dim_customer.head()

,customer_id,customer_unique_id,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,campinas,SP

**dim_seller**

In [38]:
dim_seller = sellers_silver[[
    'seller_id',
    'seller_city',
    'seller_state'
]].copy()

print("Dimension Seller Created")
print(dim_seller.shape)

Dimension Seller Created
(3095, 3)

**dim_product**

In [39]:
dim_product = products_silver[[
    'product_id',
    'product_category_name',
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm'
]].copy()

print("Dimension Product Created")
print(dim_product.shape)

Dimension Product Created
(32951, 6)

**fact_payments**

In [40]:
fact_payments = payments_silver[[
    'order_id',
    'payment_type',
    'payment_installments',
    'payment_value'
]].copy()

print("Fact Payments Created")
print(fact_payments.shape)

Fact Payments Created
(103886, 4)

**fact_reviews**

In [41]:
fact_reviews = reviews_silver[[
    'review_id',
    'order_id',
    'review_score'
]].copy()

print("Fact Reviews Created")
print(fact_reviews.shape)

Fact Reviews Created
(99224, 3)

**1.Average Delivery Days**

In [42]:
avg_delivery = fact_orders['delivery_days'].mean()

print("Average Delivery Days:", round(avg_delivery,2))

Average Delivery Days: 12.09

**2.Average Delay Days**

In [43]:
avg_delay = fact_orders['delay_days'].mean()

print("Average Delay Days:", round(avg_delay,2))

Average Delay Days: -11.88

**3.Order Status Distribution**

In [44]:
fact_orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

**4.Payment Type Distribution**

In [45]:
fact_payments['payment_type'].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

**5.Review Score Distribution**

In [46]:
fact_reviews['review_score'].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

**Missing Fact Table**

In [47]:
fact_delivery_sla = orders_silver[[
    'order_id',
    'delivery_days',
    'delay_days'
]].copy()

print("Fact Delivery SLA Created")
print(fact_delivery_sla.shape)

Fact Delivery SLA Created
(99441, 3)

**Seller Performance Table**

In [48]:
seller_performance = order_items_silver.merge(
    fact_orders[['order_id','delay_days']],
    on='order_id',
    how='left'
)

seller_performance = seller_performance.groupby('seller_id').agg({
    'price':'sum',
    'freight_value':'sum',
    'delay_days':'mean'
}).reset_index()

seller_performance.rename(columns={
    'price':'total_sales',
    'freight_value':'total_freight',
    'delay_days':'avg_delay_days'
}, inplace=True)

seller_performance.head()

,seller_id,total_sales,total_freight,avg_delay_days
0,0015a82c2db000af6aaaf3ae2ecb0532,2685.00,63.06,-16.333333
1,001cca7ae9ae17fb1caed9dfb1094831,25080.03,8854.14,-13.213675
2,001e6ad469a905060d959994f1b41e4f,250.00,17.94,NaN
3,002100f778ceb8431b7a1020ff7ab48f,1234.50,793.66,-8.185185
4,003554e2dce176b5555353e4f3555ac8,120.00,19.38,-27.000000

**Top 10 Sellers**

In [49]:
top_sellers = seller_performance.sort_values(
    by='total_sales',
    ascending=False
)

top_sellers.head(10)

,seller_id,total_sales,total_freight,avg_delay_days
857,4869f7a5dfa277a7dca6462dcf3b52b2,229472.63,20168.07,-11.164634
1013,53243585a1d6dc2643021fd1853d8905,222776.05,13080.63,-11.605000
881,4a3ca9315b744ce9f8e9374361493884,200472.92,35067.04,-9.644433
3024,fa1c13f2614d7b5c4749cbc52fecda94,194042.03,10042.70,-10.309154
1535,7c67e1448b00f6e969d365cea6b010ab,187923.89,51612.55,-11.529889
1560,7e93a43ef30c4f03f38b393420bc753a,176431.87,6322.18,-12.161491
2643,da8622b14eb17ae2831f4ac5b9dab84a,160236.57,24955.75,-11.239018
1505,7a67c85e85bb2ce8582c35f2203ad736,141745.53,20902.85,-11.838095
192,1025f0e2d44d7041d6cf58b6550e0bfa,138968.55,33892.14,-11.104930
1824,955fee9216a65b617aa5c0531780ce60,135171.70,25430.98,-10.332880

**Average Review Score**

In [50]:
average_review_score = fact_reviews['review_score'].mean()

print("Average Review Score:", round(average_review_score,2))

Average Review Score: 4.09

**Total Revenue**

In [51]:
total_revenue = order_items_silver['price'].sum()

print("Total Revenue:", round(total_revenue,2))

Total Revenue: 13591643.7

**Gold Layer Tables**

In [52]:
fact_orders.to_csv('fact_orders.csv', index=False)

fact_payments.to_csv('fact_payments.csv', index=False)

fact_reviews.to_csv('fact_reviews.csv', index=False)

fact_delivery_sla.to_csv('fact_delivery_sla.csv', index=False)

dim_customer.to_csv('dim_customer.csv', index=False)

dim_seller.to_csv('dim_seller.csv', index=False)

dim_product.to_csv('dim_product.csv', index=False)

print("All Gold Layer Files Exported Successfully")

All Gold Layer Files Exported Successfully